### ISSUE TITLE
crashes at startup almost instantly

### ISSUE THREAD

**Issue by delveticas** [NekoX-Dev/NekoX#1060]
[logs (1).zip](https://github.com/user-attachments/files/16285616/logs.1.zip)
![Screenshot_2024-07-18-20-43-10-117_com android settings](https://github.com/user-attachments/assets/454618ab-ff28-4836-a8a8-c8a87eb52f9a)

**Comment by WankkoRee** [comment]
Same problem.

```
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 23049RAD8C
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 3414
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: nekox.messenger
[Version Name]: 9.5.8
[Version Code]: 750
[Target SDK]: 32
[Min SDK]: 19
[Error Type]: JVM
[Crash Time]: 2024-07-19T11:24:54.442
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.telegram.messenger.MessageObject.updateMessageText(MessageObject.java:345)
	at org.telegram.messenger.MessageObject.<init>(MessageObject.java:39)
	at org.telegram.messenger.MessageObject.<init>(MessageObject.java:21)
	at org.telegram.messenger.MessagesController$$ExternalSyntheticLambda174.run(R8$$SyntheticClass:287)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at org.telegram.messenger.DispatchQueue.run(DispatchQueue.java:25)
```
