### ISSUE TITLE
选择完文件点按发送时崩溃（但愿这次日志有用，无用请colse

### ISSUE THREAD

**Issue by YuMore233** [NekoX-Dev/NekoX#684]
备注：这次是Android 12
Process: nekox.messenger
PID: 11638
UID: 10306
Flags: 0x30983e44
Package: nekox.messenger v470 (8.2.7)
PID: 11638
Foreground: Yes
Process-Runtime: 34337711
Build: OnePlus/OnePlus8Pro_CH/OnePlus8Pro:12/SKQ1.210216.001/Q.202111251444:user/release-keys
Loading-Progress: 1.0

java.lang.RuntimeException: Unable to resume activity {nekox.messenger/org.telegram.ui.LaunchActivity}: java.lang.RuntimeException: You must pass an IMyLocationProvider to setMyLocationProvider()
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4933)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4972)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.RuntimeException: You must pass an IMyLocationProvider to setMyLocationProvider()
	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.setMyLocationProvider(MyLocationNewOverlay.java:4)
	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:1)
	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:14)
	at org.telegram.ui.Components.ChatAttachAlertLocationLayout.onResume(ChatAttachAlertLocationLayout.java:5)
	at org.telegram.ui.Components.ChatAttachAlert.onResume(ChatAttachAlert.java:4)
	at org.telegram.ui.ChatActivity.onResume(ChatActivity.java:13)
	at org.telegram.ui.ActionBar.ActionBarLayout.onResume(ActionBarLayout.java:17)
	at org.telegram.ui.LaunchActivity.onResume(LaunchActivity.java:21)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1491)
	at android.app.Activity.performResume(Activity.java:8281)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4923)
	... 13 more

**Comment by YuMore233** [comment]
> 看日志和openstreatmap有关 请问有稳定的复现方法吗？

点过位置然后再去发送文件便会崩溃
