### ISSUE TITLE
NekoX crashes moment after connecting to proxy

### ISSUE THREAD

**Issue by OrchidWarrior** [NekoX-Dev/NekoX#940]
java.lang.IllegalStateException: Unbalanced enter/exit
	at okio.AsyncTimeout.enter(AsyncTimeout.kt:32)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:2)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:6)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:2)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:1)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:2)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:1)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:15)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:15)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:15)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:37)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:15)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:40)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:15)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:23)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by mhamzas** [comment]
Facing the same issue
https://paste.evolution-x.org/QM1A0O

**Comment by luvletter2333** [comment]
Should be fixed in next release
